### ISSUE TITLE
GetDC() being called on an uninitiated variable

### ISSUE THREAD

**Issue by Ownasaurus** [inflex/BK-390A#9]
https://github.com/inflex/BK-390A/blob/d3eb510cdbd0412e996b3ce67df896016c6a2915/win-bk390a.cpp#L648

I'm honestly not sure why this works. That's why in PR #7 I changed the order of the lines of code. You might understand better than I do though.

**Comment by ghost** [comment]
Sorry I didn't see this in the previous PR.  Probably a good reason for us to keep PRs as small as possible focusing just on one or two changes, else I do tend to suffer from revision blindness, particularly with managing all the other projects,

Anyhow, I tried flipping around the ordering so that it wasn't using a non-initialised hstatic and it interestingly resulted in a collapsed window (but I was able to stretch it out).

**Comment by Ownasaurus** [comment]
Yes I have a fix for that in my old code. I'll get to it in a moment.

**Comment by Ownasaurus** [comment]
The order was:
1) CreateWindowW
2) GetDC & fontstuff
3) if statements to updated g.window_x and g.window_y
4) SetWindowPos(hstatic,HWND_TOP,50,50,g.window_x,g.window_y,(UINT)0);

Let me know if you want me to make another PR or if you will do it yourself.

**Comment by ghost** [comment]
Feel free to PR & test it.

**Comment by Ownasaurus** [comment]
Resolved in PR #11
